CREATE TABLE users(
   user_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
   name VARCHAR(30) NOT NULL,
   username VARCHAR(50) NOT NULl,
   password VARCHAR(60) NOT NULL,
   email VARCHAR(255) NOT NULL,
   date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE userMessages(
  message_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  from_user VARCHAR(30) NOT NULL,
  comment VARCHAR(255) NOT NULL,
  user_id INT(11) NOT NULL,
  date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);